name: validate json
on: 
  push:
    paths: ['**.json']
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dsanders11/json-schema-validate-action@v1.2.0
        with:
          schema: https://raw.githubusercontent.com/ThePandemoniumInstitute/botc-release/main/script-schema.json
          files: |
            custom/*.json
            homebrew/**/*.json