name: validate json
on: 
  pull_request:
    paths: ['**.json']
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: validate schema
        uses: dsanders11/json-schema-validate-action@v1.2.0
        with:
          schema: 'json-schema'
          files: schema.json
      - name: validate files
        uses: dsanders11/json-schema-validate-action@v1.2.0
        with:
          schema: schema.json
          files: |
            custom/*.json
            homebrew/**/*.json